apiVersion: v1
kind: Pod
metadata:
  name: iotgateway
  labels:
    purpose: iotgateway
spec:
  containers:
  - name: iotgateway-container
    image: asia.gcr.io/data-audio-175707/hackathon-nodejs-app
    env:
    - name: DB_HOST
      value: "mongo-hackathon"
    - name: DB_NAME
      value: "hackathon"
