apiVersion: v1
kind: Pod
metadata:
  name: iotgateway
  labels:
    purpose: iotgateway
spec:
  containers:
  - name: iotgateway-container
    image: asia.gcr.io/data-audio-175707/hackathon-nodejs-app
    env:
    - name: DB_HOST
      value: "mongo-hackathon"
    - name: DB_NAME
      value: "hackathon"
    - name: CLIENT_ID
      value: "qoUrp9M8yVD2gOgi9QxyPPdaDLrTz7jy"
    - name: CLIENT_SECRET
      value: "ls5tr2WFcsr1J74x"
    - name: NODE_ENV
      value: "development"
    - name: MQTT_PORT
      value: "10513"
    - name: MQTT_USERNAME
      value: "vuvawrqs"
    - name: MQTT_PASSWORD
      value: "HtWwI7a3emnC"
    - name: DEBUG
      value: "*"
