apiVersion: v1
kind: Pod
metadata:
  name: iotgateway
  labels:
    purpose: iotgateway
spec:
  containers:
  - name: iotgateway-container
    image: asia.gcr.io/data-audio-175707/hackathon-nodejs-app
    env:
    - name: DB_HOST
      value: "mongo-hackathon"
    - name: DB_NAME
      value: "hackathon"
    - name: CLIENT_ID
      value: "20yupeh39V13Ch7CQsAG36ktDhtDN8jM"
    - name: CLIENT_SECRET
      value: "O8yqGigymc3W1Vc6"
    - name: NODE_ENV
      value: "development"
    - name: MQTT_PORT
      value: "10513"
    - name: MQTT_USERNAME
      value: "test"
    - name: MQTT_PASSWORD
      value: "test"
    - name: DEBUG
      value: "*"
